version: 2.1

orbs:
  python: circleci/python@0.2.1
  gradle: circleci/gradle@2.1.0

jobs:
  python-build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: pip install pipenv
          name: Install pipenv
      - run:
          command: pipenv install --dev
          name: Install dependencies
          working_directory: ./python
      - run:
          command: pipenv run pylint data_structures
          name: Lint
          working_directory: ./python
      - run:
          command: pipenv run pytest
          name: Test
          working_directory: ./python

workflows:
  main:
    jobs:
      - python-build-and-test
      - gradle/test:
          app_src_directory: java
